
services:
  db:
    image: postgres:16
    container_name: shareit-db
    restart: always
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - shareit-db-data:/var/lib/postgresql/data

volumes:
  shareit-db-data: